### ISSUE TITLE
Poor contrast between new messages in muted vs not muted chats

### ISSUE THREAD

**Issue by beeb** [catppuccin/telegram#1]
The color of the badge showing unread messages for unmuted chats is close to the color of the messages in muted chats.

This makes it hard to spot which chats have relevant messages to read.

Compare Ctp:

![image](https://user-images.githubusercontent.com/703631/189482475-c5d02bf5-0e17-4d85-a9e8-5951c78e100b.png)

With default dark theme:

![image](https://user-images.githubusercontent.com/703631/189482500-4c7eb04e-8ab5-49db-8148-4469c86a2892.png)

Would be great to have something that pops out a little more!
Thanks

**Comment by andreasgrafen** [comment]
Cheers! Thanks for letting me know. The Telegram theme def. needs a complete overhaul and also an update to v2 as well. While this is in the making, there is no ETA on that yet – sadly. But I'll keep this on top of my ToDo list for Telegram. ^—^

**Comment by andreasgrafen** [comment]
Update: With the update to the new palettes the contrast got increased drastically. While this currently is available for Android only; Telegram Desktop will follow soon.

<img width="856" alt="Screenshot 2022-10-03 at 16 17 51" src="https://user-images.githubusercontent.com/35840154/193600365-0033f133-bd28-4dab-90ba-cd96b98fe843.png">

I'd close this issue for now as this has been fixed with [f3d55c7](https://github.com/catppuccin/telegram/commit/f3d55c7ba2ec89d70b31683b21d9021405ce0ef7). c:
